baseURL = 'https://xdream8.github.io/'
languageCode = 'en-us'
paginate = 8
summaryLength = 8
title = 'XDream8'

[markup.goldmark.renderer]
unsafe = true

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/XDream8"
weight = 1
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 5
[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 95
[[menu.main]]
identifier = "tags"
name = "Tag"
url = "/tags/"
weight = 99

[[menu.second]]
identifier = "contact"
name = "Contact"
url = "https://github.com/XDream8/XDream8/issues/new"
weight = 1
[[menu.second]]
identifier = "privacy"
name = "Privacy"
url = "/privacy"
weight = 2

[params]
author = "XDream8"
description = "Hello there, I’m XDream8"
menu_item_separator = " - "

[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/XDream8"
[[params.social]]
icon = "rss"
name = "RSS Feed"
url = "/index.xml"

[outputs]
home = ["HTML", "RSS"]
